# permissions for end users to view o2ims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: o2-ims-operator
    app.kubernetes.io/managed-by: kustomize
  name: o2ims-viewer-role
rules:
- apiGroups:
  - ovran.example.com
  resources:
  - o2ims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ovran.example.com
  resources:
  - o2ims/status
  verbs:
  - get
